version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      # Lưu dữ liệu DynamoDB vào ./data/dynamodb-local
      - ./data/dynamodb-local:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    user: root

  rabbitmq-local:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-local
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      # Lưu dữ liệu RabbitMQ vào ./data/rabbitmq-local
      - ./data/rabbitmq-local:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis-local:
    image: redis:alpine
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      # Lưu dữ liệu Redis vào ./data/redis-local
      - ./data/redis-local:/data
    # Bật AOF để Redis ghi dữ liệu xuống file ngay lập tức
    command: redis-server --appendonly yes

  chat-service-api:
    build:
      context: . # Đưa ra gốc (nơi chứa thư mục chat_service)
      dockerfile: chat_service/ChatService.Api/Dockerfile
    container_name: chat-service-api
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - dynamodb-local
      - redis-local
      - rabbitmq-local
      - chat-service-worker

  chat-service-worker:
    build:
      context: . # Đưa ra gốc (nơi chứa thư mục chat_service)
      dockerfile: chat_service/ChatService.Worker/Dockerfile
    container_name: chat-service-worker
    environment:
      - DOTNET_ENVIRONMENT=Docker
    depends_on:
      - dynamodb-local
      - rabbitmq-local
      - redis-local

  api-service:
    build:
      context: ./api_service 
    container_name: api-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb-local
