spring.application.name=api_service
server.servlet.context-path=/api
spring.cloud.aws.dynamodb.region=ap-southeast-1
spring.cloud.aws.credentials.access-key=fakeAccessKey
spring.cloud.aws.credentials.secret-key=fakeSecretKey
logging.level.software.amazon.awssdk.services.dynamodb=debug
spring.cloud.aws.dynamodb.endpoint=http://dynamodb-local:8000
spring.threads.virtual.enabled=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
