spring.application.name=api_service
server.servlet.context-path=/api
spring.cloud.aws.dynamodb.region=ap-southeast-1
spring.cloud.aws.credentials.access-key=fakeAccessKey
spring.cloud.aws.credentials.secret-key=fakeSecretKey
logging.level.software.amazon.awssdk.services.dynamodb=debug
spring.cloud.aws.dynamodb.endpoint=http://localhost:8000
# spring.flyway.enabled=true
